version: '2'
services:

  postgres-query:
    image: postgres:13
    container_name: postgres_query
    environment:
      POSTGRES_DB: cqrs-read-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_query_data:/var/lib/postgresql/data

volumes:
  postgres_query_data: